### ISSUE TITLE
Documentation indentation

### ISSUE THREAD

**Issue by mfouesneau** [heavenshell/vim-pydocstring#1]
Hi, just found your plugin which will save me a lot of time.

However I did one quick change in your code in order to keep the default indentation of the block even when the template contains more than keywords. Patch is below.

```
diff --git a/autoload/pydocstring.vim b/autoload/pydocstring.vim
index 19d3f23..14e6645 100644
--- a/autoload/pydocstring.vim
+++ b/autoload/pydocstring.vim
@@ -99,7 +99,7 @@ function! s:builddocstring(strs, indent)
       elseif line == '"""'
         call add(docstrings, a:indent . line)
       else
-        call add(docstrings, line)
+        call add(docstrings, a:indent . line)
       endif
     endfor
     let tmpl = substitute(join(docstrings, "\n"), "\n$", '', '')
```

I also think it would be cleaner to put everything into ftplugins/python so that you do not load your plugin when you do not need it.

**Comment by delminskii** [comment]
Yeah, I have the same problem which TS has. Docstring is in the same level as def\class definition has.

**Comment by heavenshell** [comment]
@delminskii 
Could you show me step to reproduce(please show me minimum Python file)?
I can't reproduce it...

**Comment by delminskii** [comment]
@heavenshell 
Here's the example:
<pre>
class Test(object):
"""Test"""

    def __init__(self):
    """__init__"""
        pass


def hello(i, p, t):
"""hello

:param i:
:param p:
:param t:
"""
    a = p + t
    return i * a
</pre>

**Comment by delminskii** [comment]
PEP8 recommends setting docstring on the same level as class'\function's body has. I have pyflake8 vim plugin and it tells that there's indentation before <pre>"""</pre> in docstring

**Comment by heavenshell** [comment]
@delminskii 
Thanks.
Here is my result.

```python
class Test(object):
    """Test"""
    def __init__(self):
        pass
      

def hello(i, p, t):
    """hello

    :param i:
    :param p:
    :param t:
    """
    a = p + t
    return i * a
```
Looks fine.
Could you show me the result of paste mode?

```
:echo &paste 
```
If you use `set paste` it's broke indent.

>PEP8 recommends setting docstring on the same level as class'\function's body has. 

I know that.

**Comment by delminskii** [comment]
@heavenshell <pre>echo &paste</pre> returns 0. It's in my normal workflow. But if I want pasting code from somewhere I just press <F2> and mode toggles for normal pasting (with source indentation). Otherwise, that doesn't matter.

**Comment by heavenshell** [comment]
@delminskii 
Thanks.

Huum.
How about your tab settings.
Could you show me `tabstop`, `shiftwidth`, `softtabstop`, `expandtab`?
My .vimrc's settings are following.
```viml
autocmd FileType python setlocal tabstop=4 shiftwidth=4 softtabstop=4 expandtab
```

**Comment by delminskii** [comment]
@heavenshell 
<pre>tabstop</pre> and <pre>shiftwidth</pre> are the same, <pre>:echo &softtabstop</pre> returns <pre>0</pre>
So, there's the next lines in my .vimrc:
<pre>
  8 " --------------------------CUSTOM-----------------------------                  
  9 " Settings to perform spaces number, which will be replace for \t                
 10 set tabstop=4                                                                                                                                                                                                                   
 11 set shiftwidth=4                                                                 
 12 set smarttab                                                                     
 13 set et                                      " Enable autoreplacement by default  
 14 set wrap                                    " Strings' replacement 
</pre>

**Comment by mfouesneau** [comment]
@delminskii maybe you have some indent/autoindent configuration that conflicts with something else?

**Comment by heavenshell** [comment]
@delminskii 
Thanks.
I got it. pydocstring.vim depends on `softtabstop`.
So, currently you should set `softtabstop`.

Should we introduce something like `let g:pydocstring_default_indent_size`?
1. Check if `let g:pydocstring_default_indent_size` is set, use it.
2. if `let g:pydocstring_default_indent_size` is not set, use `softtabstop`.

What do you think?

**Comment by delminskii** [comment]
@heavenshell 
I don't know... Is it possible using <pre>g:pydocstring_default_indent_size</pre> instead of softtabstop? (Sorry, I don't know vimL\vim-script); Just set <pre>g:pydocstring_default_indent_size</pre> 4 by default and then check if softtabstop is different relatevly <pre>g:pydocstring_default_indent_size</pre>. If it's different then use softtabstop for indentation. And don't forget to write about it in README in repo. Anyway, it all depends on you.

**Comment by delminskii** [comment]
@heavenshell Also I think it'd be a cool to change key for setting docstring. For example, I use <C-h,j,k,l> to move between windows in vim

**Comment by heavenshell** [comment]
@delminskii 
Ok, let me confirm.

If you set `set softtabstop=4`, pydocstring.vim works fine?

> Also I think it'd be a cool to have possibility to change key for setting docstring.

Try following.
```viml
nmap <silent> <C-_> <Plug>(pydocstring)
```

**Comment by delminskii** [comment]
@heavenshell yeah, with softtabstop=4 everything works fine. I set `nmap` directly into .vimrc and everything is ok. Thanks.

**Comment by heavenshell** [comment]
@delminskii 
Thanks. Great :+1: 
I added docs to README.
https://github.com/heavenshell/vim-pydocstring/commit/9a36655c5de746baa407af84b8bb610555f21e4e
