### ISSUE TITLE
Custom template not found

### ISSUE THREAD

**Issue by StotoV** [heavenshell/vim-pydocstring#101]
I created my own template at ```~/.vim/syntax/pydoc``` and specfied that in my vimrc with the following; ```let g:pydocstring_template_path = '~/.vim/syntax/pydocs'```. In the dir I created I have a class.txt, def.txt and noarg.txt.

However, whenever I execute the ```:Pydocstring``` the default template is used.

Vim version 8.2.500

**Comment by heavenshell** [comment]
Sorry, had a typo...
https://github.com/heavenshell/vim-pydocstring/pull/102/files

Please try
`let g:pydocstring_templates_path = '~/.vim/syntax/pydocs'`

**Comment by StotoV** [comment]
Yep that fixed it, thanks!
