### ISSUE TITLE
`:PydocstringFormat` isn't respecting buffer fileformat when outputting results

### ISSUE THREAD

**Issue by SkyLeach** [heavenshell/vim-pydocstring#109]
check fileformat: `set ff`
![image](https://user-images.githubusercontent.com/940228/93003596-0aeef080-f50e-11ea-89c9-3efc40c31371.png)

run `:PydocstringFormat`
![image](https://user-images.githubusercontent.com/940228/93003621-3eca1600-f50e-11ea-8c72-211be10e9a21.png)

a *very* quick glance over the code makes me think that using '\n' (safe for posix) is the problem.  Should be \r which should input whatever line ending CR should insert based on fileformat.  I may be off, but that's my best guess.

**Comment by heavenshell** [comment]
@SkyLeach 
Thx for reporting.

I can't reproduced.
Please give me more information(steps to reproduce, OS, Vim version).
![Kapture 2020-09-13 at 14 29 49](https://user-images.githubusercontent.com/56591/93011027-ad21dd80-f5cd-11ea-9f23-4393f5e32405.gif)

**Comment by SkyLeach** [comment]
Windows 10 Home
NeoVim v0.4.4

I don't think there are any special steps.  I'm not using Cygwin or anything here, just Python 3.8 on windows with neovim.

**Comment by heavenshell** [comment]
@SkyLeach 
Works fine for me. Windows10(VirtualMachine), Vim8.2, Python3.7
![Kapture 2020-09-16 at 18 47 54](https://user-images.githubusercontent.com/56591/93341245-d0b48480-f868-11ea-88d0-45347d5798ae.gif)

This vim has vim-pydocstring only and no vimrc.
So, I think this is your env's problem.

Please try minimum vimrc(Load only vim-pydocstring).
