### ISSUE TITLE
Is module docstring supported?

### ISSUE THREAD

**Issue by FrankRouter** [heavenshell/vim-pydocstring#11]

**Comment by heavenshell** [comment]
Sorry what do you mean `module docstring`?

Could you show me example?

**Comment by FrankRouter** [comment]
> The docstring for a module should generally list the classes, exceptions and functions (and any other objects) that are exported by the module, with a one-line summary of each. (These summaries generally give less detail than the summary line in the object's docstring.) The docstring for a package (i.e., the docstring of the package's __init__.py module) should also list the modules and subpackages exported by the package.

An example of docstring of current python file.
""" XXX interfece for XXX.
Author: abc
"""
Reference: [PEP 257](https://www.python.org/dev/peps/pep-0257/)

**Comment by heavenshell** [comment]
Thanks. pydocstring.vim can't support `module docstring`.

pydocstring.vim generate docstring from `class`, `function` and `method` signature.

If you want set header comment, you can use Vim's [skeleton](http://vimdoc.sourceforge.net/htmldoc/autocmd.html#skeleton).

Or if you want more dynamically, you can use [sonictemplate.vim](https://github.com/mattn/sonictemplate-vim/).

**Comment by FrankRouter** [comment]
Got it. I'll have a try. Thanks.
