### ISSUE TITLE
How to get variables returned? 

### ISSUE THREAD

**Issue by demonlord1997** [heavenshell/vim-pydocstring#126]
```py
def foo(a:int, b:int) -> int:
    c = a+b
    return c
```
I want to generate ：
```py
def foo(a:int, b:int) -> int:
    """foo.

    Parameters
    ----------
    a : int
        a
    b : int
        b

    Returns
    -------
    c : int

    """
    c = a+b
    return c
```
But, I get:
```py
def foo(a:int, b:int) -> int:
    """foo.

    Parameters
    ----------
    a : int
        a
    b : int
        b

    Returns
    -------
    int

    """
    c = a+b
    return c

```
It cannot get  variables returned.

**Comment by heavenshell** [comment]
Currently it's impossible to get return value from function/method signature.

Signature does not include any value only type.
I know AST can get multiple return statement, but I don't want to enumerate all return variables.

**Comment by heavenshell** [comment]
If you want to enumerate return values, please show me your use case.

**Comment by demonlord1997** [comment]
> Currently it's impossible to get return value from function/method signature.
> 
> Signature does not include any value only type.
> I know AST can get multiple return statement, but I don't want to enumerate all return variables.
Thanks for your answer
