### ISSUE TITLE
Error when trying :Pydocstring. 

### ISSUE THREAD

**Issue by qazip** [heavenshell/vim-pydocstring#128]
Here is a screenshot of the error. Any ideas what's happening? I get that when I am in a function line and type `:Pydocstring`.

![pydocstring](https://user-images.githubusercontent.com/16175716/117416739-35f8db00-af09-11eb-8994-2fb4e885136a.png)

For people who are searching for the same error, the error's text is:

`Error detected while processing function pydocstring#insert[32] ..<SNR>124_execute:`
`E903: Process Failed to start: no such file or directory "/usr/local/bin/zsh"`

**Comment by heavenshell** [comment]
@qazip 
Hi, Thank you for reporting.

Fmm, strange. In my env, works fine.
Did you install py-doq(dependency library)?
Could you show me step to reproduce?

- How to install py-doq
- How to startup Vim and execute `:Pydocstring`
- does using minimum vimrc reproduce?

```vimrc
set nocompatible
filetype off

" Add pydocstring folder into rtp
set rtp^=/path/to/vim-pydocstring
filetype plugin indent on
```

**Comment by qazip** [comment]
With the minimal config it works.

Install:
`pip3 install --user doq`
- Open neovim, go to a function def and do :Pydocstring. Doing this I get the error.

Since the min config works, it is probably something on my end..

**Comment by yaegassy** [comment]
@qazip Do you have a `set shell` setting in your "vimrc/init.vim"?

Does `/usr/local/bin/zsh` exist as a command?

"Neovim" seems to give the same error with the `:Pydocstring` command if the "set shell" setting is incorrect.

**Repro(/usr/local/bin/dummy)**:

<img width="875" alt="vim-pydocstring-issue-128" src="https://user-images.githubusercontent.com/188642/119293686-e8f96080-bc8d-11eb-87d5-3321b26c93db.png">

**Comment by qazip** [comment]
Hi!

Sorry, I forgot about this! I had some other problem with another plugin so I deleted everything and re-did plugupdate. It seems to have fixed both the other plugin and pydocstring. Why? Dunno.
