### ISSUE TITLE
[Feature Request] Add support for type hint syntax

### ISSUE THREAD

**Issue by letientai299** [heavenshell/vim-pydocstring#13]
Please add support for [Type Hint (PEP 484)](https://www.python.org/dev/peps/pep-0484/) in Python 3.

As of now, pydocstring create the following result.
```python
def foo(n: int ) -> bool:
    """foo

    :param n:int)->bool::
    """
    return True
```

It would be much better if we could get following result:

```python
def foo(n: int ) -> bool:
    """foo

    :param n (int):

    :return (bool):
    """
    return True
"""

**Comment by heavenshell** [comment]
@letientai299 
Yeah, I will support it.
But this is no easy, so stay tuned.

If you don't wait my implementation, patches are welcome 😊

**Comment by heavenshell** [comment]
Done #15
