### ISSUE TITLE
Not an editor command: Pydocstring

### ISSUE THREAD

**Issue by kashiwachen** [heavenshell/vim-pydocstring#133]
@heavenshell Hello there. I am having the same problem as #99. I have tried the solution but it didn't work.
Here is the information you may need:
```
NVIM: v0.4.4
iTerm2: Build 3.4.6
```
Error:
```
E492: Not an editor command: Pydocstring
```
I use `:PlugInstall` to install your plug, and use `:PlugStatus` to check whether it is installed successfully. `:PlugStatus` shows `- vim-pydocstring: OK`.
I also try 
```
cat sample.py | ~/.pyenv/shims/doq
```
to see whether `doq` is installed, the command returns
```
def foo(a):
    """foo.

    :param a:
    """
    return a
```
So I guess, it is installed successfully.
Looking forward to your response

**Comment by heavenshell** [comment]
@kashiwachen 
Hi, Thank you for reporting.

Could you please try following minimal vimrc works fine? 🙏 

```vimrc
set nocompatible
filetype off

" Add pydocstring folder into rtp
set rtp^=/path/to/vim-pydocstring
filetype plugin indent on
```

And run following steps

1. nvim -u /path/to/min_vimrc sample.py
2. move cursor to def line
3. `: Pydocstring`

**Comment by kashiwachen** [comment]
Thank you for your super fast response. Your minimal vimrc method works well. I am not familiar with vim, is this problem related to `rtp` path setting?
I add this setting according to the instruction.
`let g:pydocstring_doq_path = '~/.pyenv/shims/doq'`

**Comment by heavenshell** [comment]
```vim
autocmd!
set nocompatible

call plug#begin()
  Plug 'heavenshell/vim-pydocstring', { 'do': 'make install' }
call plug#end()
syntax enable
filetype plugin indent on
```
I Tried to use vim-plug(In docker).
But works fine for me...

https://user-images.githubusercontent.com/56591/119002165-9850e180-b9c7-11eb-88da-2dbc0dfaf780.mp4

Could you show me rtp path?
```
:echo &rtp
```

Mine
```
/home/s_ohyanagi/.config/nvim,/home/s_ohyanagi/.config/nvim/plugged/vim-pydocstring,/etc/xdg/nvim,/home/s_ohyanagi/.local/share/nvim/site,/usr/local/share/nvim/site,/usr/share/nvim/site,/usr/share/nvim/runtime,/usr/share/nvim/runtime/pack/dist/opt/matchit,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,/home/s_ohyanagi/.local/share/nvim/site/after,/etc/xdg/nvim/after,/home/s_ohyanagi/.config/nvim/after
```

**Comment by kashiwachen** [comment]
Here is my rtp path.
```
/Users/oscar/.config/nvim,/Users/oscar/.config/nvim/plugged/tokyonight-vim,/Users/oscar/.config/nvim/plugged/onedark.vim,/Users/oscar/.config/nvim/plugged/indentLine,/Users/oscar
/.config/nvim/plugged/nerdtree,/Users/oscar/.config/nvim/plugged/coc.nvim,/Users/oscar/.config/nvim/plugged/delimitMate,/Users/oscar/.config/nvim/plugged/vim-airline,/Users/oscar
/.config/nvim/plugged/vim-airline-themes,/Users/oscar/.config/nvim/plugged/vim-pydocstring,/etc/xdg/nvim,/Users/oscar/.local/share/nvim/site,/usr/local/share/nvim/site,/usr/share
/nvim/site,/usr/local/Cellar/neovim/0.4.4/share/nvim/runtime,/usr/local/Cellar/neovim/0.4.4/share/nvim/runtime/pack/dist/opt/matchit,/usr/share/nvim/site/after,/usr/local/share/n
vim/site/after,/Users/oscar/.local/share/nvim/site/after,/etc/xdg/nvim/after,/Users/oscar/.config/nvim/plugged/indentLine/after,/Users/oscar/.config/nvim/after
```
> Did you install doq with pyenv?

Yes I did install doq with pyenv.
About this, I also tried to install vim-pydocstring with vim-plug at the beginning, however, it doesn't work. So I try to install doq manually at last.

**Comment by heavenshell** [comment]
ah~

how about this?

```vim
Plug 'heavenshell/vim-pydocstring', { 'do': 'make install', 'for': 'python' }
```
ref: https://github.com/junegunn/vim-plug#plug-options

**Comment by heavenshell** [comment]
https://github.com/kashiwachen/dotfiles/blob/e300a248fa67ca53f3fc99e85d4ee700409ff3af/.config/nvim/init.vim#L63

You should not off plugin.
IMO you don't need this for reset indent size.

**Comment by kashiwachen** [comment]
> https://github.com/kashiwachen/dotfiles/blob/e300a248fa67ca53f3fc99e85d4ee700409ff3af/.config/nvim/init.vim#L63
> 
> You should not off plugin.
> IMO you don't need this for reset indent size.
> 
> `:Pydocstring` is set at `ftplugin/pydocstring.vim`. So, if `filetype plugin off` was set, can't read command.

Thank you so much, now it works perfectly.
