### ISSUE TITLE
Pydocstring overrides C-L shortcut

### ISSUE THREAD

**Issue by data-stepper** [heavenshell/vim-pydocstring#135]
In my vimrc, I use the shortcut(s) C-[hjkl] to move between splits.

When I now started using pydocstring, it overrode the shortcut for switching to the right split (C-L).
I know from the docs that I can change the default keymapping for pydocstring, but I can't make it unmap
C-L.

I've tried using VimEnter to get around this without any luck so far :(

Maybe there is an easy solution to this, regards and thanks in advance for any help

**Comment by heavenshell** [comment]
@data-stepper 
Hi, Thank you for using my plugin.

Did you set following like below?

```vimrc
let g:pydocstring_enable_mapping = 0
```

**Comment by data-stepper** [comment]
Thanks it fixed my issue.

I didn't find this in the README, maybe an idea to add it as I think it's quite useful?

**Comment by heavenshell** [comment]
It's mentioned at doc.

https://github.com/heavenshell/vim-pydocstring/blob/master/doc/pydocstring.txt#L197-L205
