### ISSUE TITLE
Only default template format working

### ISSUE THREAD

**Issue by nettrino** [heavenshell/vim-pydocstring#140]
Hello,

I am using a vim-pydocstring in a vanilla installation of lunarvim stable with nvim 0.7.2. Only the default template is supported, and I can not switch to numpy nor a custom template. The respective config is 
```  
{
    "heavenshell/vim-pydocstring",
    config = function()
     vim.cmd("let g:pydocstring_formatter='numpy'")
    end,
  },
  ```
I have also tried 
```  
{
    "heavenshell/vim-pydocstring",
    config = function()
      vim.cmd("let g:pydocstring_formatter='cnumpy'")
      vim.cmd("let g:pydocstring_templates_path='/Users/nettrino/.config/doq/templates/cnumpy'")
    end,
  },
  ```

Do note that running

`cat file.py | doq --style=string --formatter=cnumpy --omit=self,cls --indent=4 --template_path=/Users/nettrino/.config/doq/templates/cnumpy` works fine and generates the output.

Would it be possible to allow the user to overwrite the command that is going to be running each time for doq? this will allow for easy fixing of issues like the above. Happy to provide any debugging information as needed.

**Comment by heavenshell** [comment]
@nettrino Sorry I did not notice this issue.
I don't use Neovim and I don't know lua.

>Would it be possible to allow the user to overwrite the command that is going to be running each time for doq? 

What do you mean?

**Comment by nettrino** [comment]
@heavenshell no worries - basically I was asking for the addition of an option that allows bypassing the default doq command (e.g., in https://github.com/heavenshell/vim-pydocstring/blob/e8115fecbb3aaf79ad72791008e14e1b7cbd90e6/autoload/pydocstring.vim#L157). This would allow users to more easily customise the plugin for their env
