### ISSUE TITLE
Remove default mapping

### ISSUE THREAD

**Issue by jjshoots** [heavenshell/vim-pydocstring#141]
Hi, this is a great plugin, but is there a reason why there is a default mapping defined [here](https://github.com/heavenshell/vim-pydocstring/blob/master/ftplugin/python/pydocstring.vim#L21)?

This took me awhile to find and it cannot be overridden either.

**Comment by SamirPonto** [comment]
You can deactivate this <C-l>
like: 
vim.cmd([[
let g:pydocstring_enable_mapping = 0
]])
on your init.lua or
let g:pydocstring_enable_mapping=0 
if you're using init.vim
