### ISSUE TITLE
Indentation problem

### ISSUE THREAD

**Issue by nipunsadvilkar** [heavenshell/vim-pydocstring#20]
with and without `autocmd FileType python setlocal tabstop=4 shiftwidth=4 softtabstop=4 expandtab`
results are like this only:
```
def foo(a, b, c):
    """foo

        :param a:
            :param b:
                :param c:
                    """
```
Input from anyone would be helpful.

**Comment by heavenshell** [comment]
Strange.
My setting is exactly same as you.

```viml
autocmd FileType python,php,perl,java,c setlocal tabstop=4 shiftwidth=4 softtabstop=4 expandtab
```

```python
def foo(a, b, c):
    """foo

    :param a:
    :param b:
    :param c:
    """
    pass
```

Can you show me following command output?
```
:verbose set tabletop
```
My output is
```
  tabstop=4
        Last set from ~/.vimrc
```

**Comment by nipunsadvilkar** [comment]
@heavenshell : you mean `:verbose set tabstop` right?

My output is:

```
  tabstop=4                                                                                                                                             
        Last set from ~/.space-vim/layers/+lang/python/config.vim 
```

**Comment by heavenshell** [comment]
ah, typo 😰 
Thx.

hmm, 
```
autocmd FileType python setlocal tabstop=4 shiftwidth=4 softtabstop=4 expand tab
```
was written at `~/.space-vim/layers/+lang/python/config.vim`?

what about another `shiftwidth`, `softtabstop`, `expandtab`?

**Comment by nipunsadvilkar** [comment]
Yes, all are set there only.
Attaching screenshot for reference:
![space_vim](https://cloud.githubusercontent.com/assets/15062408/24306709/8851eaaa-10e7-11e7-9512-7fe4e76adfa7.png)

**Comment by heavenshell** [comment]
Thx.
Humm, I don't know about `SpaceVim` or `space-vim` behavior.

Anyway if you open new python file and type like following,

```vim;
idef<SPACE>foo(a,<SPACE>b,<SPACE>c):<ESC><CR><TAB>pass
```
it would be like following?
```python
def foo(a, b, c):
    pass
```
before `pass` there are 4 byte space?

**Comment by nipunsadvilkar** [comment]
Tried.. problem persists :cry:

**Comment by heavenshell** [comment]
Strange...
I can't reproduce.
pydocstring's indent depend on `softtabstop`.

What if you disabled python-mode indention.
https://github.com/liuchengxu/space-vim/blob/master/layers/%2Blang/python/config.vim#L45

**Comment by nipunsadvilkar** [comment]
Good suggestion..Thanks but not working...:(

**Comment by heavenshell** [comment]
Is there anything about indent plugins?

What about if you don't use space-vim things.
Just use plan Vim(latest version is also good) and pydocstrings.vim only.

**Comment by heavenshell** [comment]
Can't reproduce this.
