### ISSUE TITLE
Return Type

### ISSUE THREAD

**Issue by schtibe** [heavenshell/vim-pydocstring#22]
Apparently, when looking at the multi.txt, the :rtype: would be generated as well.
Yet I cannot generate a docstring containing a rtype.. how is this done?

**Comment by heavenshell** [comment]
You should write type hints.

```python
def hello(name: str) -> str:
   return 'hello {0}'.format(name)
```

Generate like following.

```python
def hello(name: str) -> str:
    """hello

    :param name:
    :type name: str

    :rtype: str
    """
    return 'hello {0}'.format(name)
```

**Comment by schtibe** [comment]
Awesome, thank you!
