### ISSUE TITLE
Return type strips period from type name

### ISSUE THREAD

**Issue by avcopan** [heavenshell/vim-pydocstring#28]
I just noticed that a signature of the form
```
def moment(weights: tuple, coords: numpy.ndarray) -> numpy.ndarray:
```
results in the following docstring
```
    """moment

    :param weights:
    :type weights: tuple
    :param coords:
    :type coords: numpy.ndarray

    :rtype: numpyndarray
    """
```
where the period has been stripped from `numpy.ndarray` in the return type.  It's easy to work around, but I thought I'd register my observation here in case you weren't aware.

Nice plugin, by the way!  Very useful.

**Comment by heavenshell** [comment]
@avcopan Thx for reporting issue.
I'll investigate this later. Please wait a while ☺️

**Comment by heavenshell** [comment]
@avcopan Fixed. Please try.

**Comment by avcopan** [comment]
It works -- thanks!
