### ISSUE TITLE
does this also support Google Docstring Style?

### ISSUE THREAD

**Issue by dhfromkorea** [heavenshell/vim-pydocstring#45]
Thank you for making and sharing this. Is there a way to easily extend this package to Google style?

**Comment by heavenshell** [comment]
@dhfromkorea 
Sorry for late response.

I don't know what is Google style docstring.
Could you show me sample?

```python
def foo(arg1, arg2=None):
   pass
```

What should pydocstring.vim generate?

**Comment by samizdis** [comment]
There's a nice overview of docstring styles here:
https://stackoverflow.com/questions/3898572/what-is-the-standard-python-docstring-format

The actual spec is at https://google.github.io/styleguide/pyguide.html?showone=Comments#Comments , but there's an example at https://stackoverflow.com/a/8109339/361867

**Comment by heavenshell** [comment]
@samizdis 
Thank you for comment.

Maybe you can set multi.txt like following.
```
"""{{_header_}}

{{_indent_}}Args:
{{_indent_}}{{_args_}}:

{{_indent_}}Returns:
"""
```

Function singature.
```python
def add_value(self, arg1, arg2):
    pass
```
would be genereate like following
```python
def add_value(self, arg1, arg2):
    """add_value

    Args:
        arg1:
        arg2:

    Returns:
    """
    pass

```

**Comment by dhfromkorea** [comment]
Thank you so much!

**Comment by yifeikong** [comment]
Could this be included in the default templates and add an option like `g:pydocstring_style = google`?

**Comment by heavenshell** [comment]
@yifeikong 
No.
But you can set your own path like

```viml
let g:pydocstring_templates_dir = '/path/to/your/templates/google'
```
You can put your own templates to the path.

**Comment by Trashcleaner** [comment]
Hello, this issue is very helpful. Could you please add the manual how to set the new template to the README section. I think it would help more people :)
Thank you very much.

**Comment by heavenshell** [comment]
@Trashcleaner 
`doc/pydocstring.vim` was mentioned about formatter, but I added to README.rst

btw, documentation PRs are very very welcome 😉
