### ISSUE TITLE
default parameter problem

### ISSUE THREAD

**Issue by muahdib69** [heavenshell/vim-pydocstring#46]
If you add type hinting with default values, the doc string created is messed up:

```
 def get_last(self, product: str = None):
        """get_last

        :param None:
        """
        if not product:
            product = self._default_product
```

**Comment by heavenshell** [comment]
@muahdib69 Thx for reporting this.
This is a bug...

May be we should generate like followings?

```
def get_last(self, product: str = None):
    """get_last

    :param product:
    :type product: str
    """
```

Type hinting is very complex to parse by Vim script.
Please stay tuned...
