### ISSUE TITLE
Update a docstring

### ISSUE THREAD

**Issue by muahdib69** [heavenshell/vim-pydocstring#47]
Would it be possible to have a upgrade function? I created the function and inserted the docstring, then I modfie the first line to be some description.

Now I add some parameters and recreate the docstring, what would be great is that the current docstring be deleted, but the first line (and maybe until the parameter definition and text after the parameters) be kept intact. 

best

**Comment by heavenshell** [comment]
I understood your requirements, but sorry currently no.
It's too complicated and I have no idea to implement this.

Please read https://github.com/heavenshell/vim-pydocstring/issues/16
