### ISSUE TITLE
E117: Unknown function: pydocstring#insert  

### ISSUE THREAD

**Issue by rishiba** [heavenshell/vim-pydocstring#48]
Unable to insert the docstring. Getting the mentioned error.

**Comment by heavenshell** [comment]
Rack of informations...
How did you install?

```viml
let s:save_cpo = &cpo
set cpo&vim

let rtps = split(&rtp, ',')
let ret = 0
for r in rtps
  if r =~ 'pydocstring'
    let ret = 1
  endif
endfor

if ret == 0
  echomsg 'No pydocstring at rap'
else
  echomsg 'pydocstring is installed'
endif

let &cpo = s:save_cpo
unlet s:save_cpo
```

- Save above Vim script to your local such as `a.vim`.
- `:so a.vim`
- `:message`

If you install pydocstring not correctly, message should show `No pydocstring at rtp` and you should install to right place.

**Comment by heavenshell** [comment]
Can't reproduce and need more information for solve this.
