### ISSUE TITLE
Configuration option for docstring style

### ISSUE THREAD

**Issue by JPFrancoia** [heavenshell/vim-pydocstring#50]
Hi,

I think this plugin is great, it seems to be an equivalent to autoDocstring for VScode.

As you might have seen in the issues, people ask for other docstring styles (ex: Google, numpy) than the default one.

Would it be possible to setup an option, so the users could choose (in their vimrc) which template to use?

Best

**Comment by JPFrancoia** [comment]
Never mind, I found the ```g:pydocstring_templates_dir``` option, which does more or less what I want.

**Comment by heavenshell** [comment]
np 😉
