### ISSUE TITLE
Default value for argument is used in place of argument's name

### ISSUE THREAD

**Issue by JPFrancoia** [heavenshell/vim-pydocstring#57]
I have this function:

```python
    def addInputPercentage(
        self,
        name: str,
        height_per: float = 100,
        angle: float = 180,
        diameter: Optional[float] = None,
        external: bool = False,
    ) -> None:
```

And generating a docstring with this plugin yielded:

```
        """addInputPercentage

        Args:
            name (str):
            100:
            180:
            diameter (Optional[float]):
            None:
            False:

        Returns:
            None
        """
```

The default value for the type-hinted argument was used instead of the argument's name in the docstring.

I think it's a bug.

**Comment by heavenshell** [comment]
Yep. Sorry, this is a bug.
Currently, type hint and keyword argument combination have problem.
I'm working this. Please stay tuned.

**Comment by heavenshell** [comment]
Ver2.0.0 was released.
Type hints and default keyword combination's bug was resolved
