### ISSUE TITLE
New vim-pydocstring plan

### ISSUE THREAD

**Issue by heavenshell** [heavenshell/vim-pydocstring#63]
## Current problems of vim-pydocstrings

- Not maintanable code
  - Parse arguments by regex is very hard and buggy
  - Combination of Typings and default value are very complex
- Template file is not extendable
  - Use template engine?
  - Jinja2 is good but too much

## How(idea)
- Use Python3's ast module and Vim8's job and channel
- Pick code sigunature and pass to parser script via job and channel
- Parser script parse signature and return JSON

e.g.
```python
def foo(arg1, arg2: List[int, str]=[1, 'foo']) -> None:
   pass
```
```json
{
  "name": "foo",
  "args": [
     { "arg": "arg1", "type": "", "default": ""},
     { "arg": "arg2", "type": "List[int, str]", "default": "[1, 'foo']"},
   ],
   "rtype": "None"
}
```
- vim-pydocstring receive JSON and put to template

**Comment by heavenshell** [comment]
2.0.0 was released 🎉

**Comment by yzlnew** [comment]
Will Neovim be supported in the future?

**Comment by heavenshell** [comment]
@yzlnew 
I'm not Neovim user, so Neovim user can send me PR 😊 
(I don't have Neovim env and I have no plan to install Neovim in my env)
