### ISSUE TITLE
Use stringed in-parenthesis default value instead of default argument

### ISSUE THREAD

**Issue by LucaZampieri** [heavenshell/vim-pydocstring#65]
As we can see below it appear that only the `lolipop` is parsed.
```python
   def plot_field_along_foil(verts, pred, gt, ylabel="Cp(lolipop)"):                                                                                                                                                      
      """plot_field_along_foil.
  
      Args:
          lolipop:
  
      Returns:
      """
```
perhaps related to #57

**Comment by heavenshell** [comment]
thx. yes. Can’t parse `()` right now.
Currently, vim-docstring can't recognize tuple or string parenthesis.

I'm working new vim-pydocstring.
https://github.com/heavenshell/vim-pydocstring/issues/63

**Comment by heavenshell** [comment]
Ver 2.0.0 was released and resolve this issue.
![Kapture 2020-02-22 at 22 53 07](https://user-images.githubusercontent.com/56591/75093568-245a3a80-55c6-11ea-8185-6ab13c6332a8.gif)
