### ISSUE TITLE
Numpy template won't work because _args_ contains :type ... :

### ISSUE THREAD

**Issue by xanderbailey** [heavenshell/vim-pydocstring#68]
It would be great to have a separate variable in the layout so we can make a proper numpy layout.

This would be great:
```
{{_indent_}}Parameters
{{_indent_}}------------

{{_args_}} :  {_type_}
{{_indent_}}    {{_args_}} is

{{_indent_}}Returns
{{_indent_}}--------
```

But at the moment if you have a function with typing then it messes everything up.

**Comment by heavenshell** [comment]
Thank you for comment.
I'm working new version.

New version will be more flexible than current version.
So please wait.

**Comment by heavenshell** [comment]
ver 2.0.0 was released.
ver 2.0.0 use Jinja2 and it can be defineed custom template.
So please try ver 2.0.0
