### ISSUE TITLE
'doq' not found.Install 'doq'

### ISSUE THREAD

**Issue by yuiant** [heavenshell/vim-pydocstring#76]
Hello.I am using neovim and I have installed doq.And I have set g:pydocstring_doq_path in my init.vim.But when i try to call :Pydocstring,the error as the title said happens.How should I make it work?please help

**Comment by heavenshell** [comment]
Currently Neovim does not support yet.
Sorry I don't have Neovim environment and Neovim knowledge.
So waiting somebody send me Neovim patch.
If you can't wait, you can send me PR 😉

**Comment by yuiant** [comment]
I see.I have fixed the problem of doq installation by using 'make install' method.But some errors still happen when I call :Pydocstring.
I am using the newest version of your plugin.
I try to look into your source code of pydocstring.vim and found that since version 1.0.0 you introduce the job control function of vim8 in your plugin,which is imcompatible with neovim's job control function.However,if i use version such as 0.6.0 of your plugin，it works well.

**Comment by heavenshell** [comment]
Sorry for inconvenience. Someday maybe some one send me Neovim PR 😉
