### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by Aletz-Arce** [heavenshell/vim-pydocstring#77]
Hi @heavenshell ,
I'm try to use fatastic plugin, but when call function for generate docstring, Vim (neovim) show me weird error about ``job_start`` function not defined.

![imagen](https://user-images.githubusercontent.com/5661038/76227465-f6d7d880-61e4-11ea-9942-ce337f607c6a.png)

Can you advice me about this error ?

**Comment by heavenshell** [comment]
Sorry. Neovim does not support yet. Only Vim8 can available now.

see #71
