### ISSUE TITLE
Unable to set custom template for docstring

### ISSUE THREAD

**Issue by rohan-97** [heavenshell/vim-pydocstring#85]
Hi @heavenshell ,

I wanted to add custom template for docstring.
I followed template shown in Readme.rst

I copied contents from [tests/templates/class.txt](https://github.com/heavenshell/vim-pydocstring/blob/master/tests/templates/class.txt) to another custom file (/root/.pydocstring/python_commenter.txt)
Following are the contents my .vimrc

```
 " Store pydocstring path and template path
 nmap <silent> <C-_> <Plug>(pydocstring)
 let g:pydocstring_doq_path = '/usr/local/bin/doq'
 let g:pydocstring_templates_path = '/root/.pydocstring/python_commenter.txt'
```
Following are the contents and permission of python_commenter.txt
```
root@geek:~/source/ksa_tests# cat /root/.pydocstring/python_commenter.txt
"""{{ name }}.
"""
root@geek:~/source/ksa_tests# ls -l /root/.pydocstring/python_commenter.txt
-rw-r--r-- 1 root root 19 Mar 29 07:22 /root/.pydocstring/python_commenter.txt
````
However when I open Python file using vim and try to do `:Pydocstring`
I get following error
```
Error detected while processing function <lambda>1[1]..<SNR>105_callback:
line    1:
E474: Invalid argument
E899: Argument of reverse() must be a List or Blob
E474: Invalid argument
E899: Argument of reverse() must be a List or Blob
E474: Invalid argument
E899: Argument of reverse() must be a List or Blob
E474: Invalid argument
E899: Argument of reverse() must be a List or Blob
E474: Invalid argument
E899: Argument of reverse() must be a List or Blob
E474: Invalid argument
E899: Argument of reverse() must be a List or Blob
E474: Invalid argument
E899: Argument of reverse() must be a List or Blob
E474: Invalid argument
E899: Argument of reverse() must be a List or Blob
E474: Invalid argument
E899: Argument of reverse() must be a List or Blob
E474: Invalid argument
E899: Argument of reverse() must be a List or Blob
E474: Invalid argument
E899: Argument of reverse() must be a List or Blob
E474: Invalid argument
E899: Argument of reverse() must be a List or Blob
E474: Invalid argument
E899: Argument of reverse() must be a List or Blob
E474: Invalid argument
E899: Argument of reverse() must be a List or Blob
E474: Invalid argument
E899: Argument of reverse() must be a List or Blob
E474: Invalid argument
E899: Argument of reverse() must be a List or Blob
E474: Invalid argument
E899: Argument of reverse() must be a List or Blob
E474: Invalid argument
E899: Argument of reverse() must be a List or Blob
E474: Invalid argument
E899: Argument of reverse() must be a List or Blob
E474: Invalid argument
-- More --
```
I searched for reverse in this repository and found one occurance in
[line 51 of /autoload/pydocstring.vim](https://github.com/heavenshell/vim-pydocstring/blob/master/autoload/pydocstring.vim#L51)

Based on error, I think json_decode(a:msg) is not returning List or Blob, whereas reverse() requires List of Blob.

Please let me know whether this information was enough or you want some more information in order to reproduce this issue.

Or I am doing this in a wrong way.

Thanks!

**Comment by heavenshell** [comment]
@rohan-97 
Thx for reporting.

1. You should add three file.
  - class.txt
  - def.txt
  - noarg.txt
2. File name should be `class.txt`, `def.txt`, `noarg.txt`

So, you may do

```
mv /root/.pydocstring/python_commenter.txt /root/.pydocstring/class.txt
cp /path/to/vim-pydocstring/tests/templates/def.txt /root/.pydocstring/def.txt
cp /path/to/vim-pydocstring/tests/templates/def.txt /root/.pydocstring/noarg.txt
```

**Comment by AleCandido** [comment]
<details><summary>I also have a similar error.</summary>
<pre>
Error detected while processing function &lt;lambda>13[1]..&lt;SNR>158_callback:
line    1:
E474: Invalid argument
E899: Argument of reverse() must be a List or Blob
E474: Invalid argument
E899: Argument of reverse() must be a List or Blob
</pre>
</details>

It seems to happen always:
- with the default templates
- with the numpy templates
- with a custom set, I have tried with all the three files you said (taken from the [example](https://github.com/heavenshell/py-doq/tree/master/examples))

while the `:PydocstringFormat` works perfectly.

Do you have any idea?

**Comment by heavenshell** [comment]
@AleCandido 
Could you show me pydocstring vimrc settings?

**Comment by AleCandido** [comment]
Yes:
```vim
let g:pydocstring_doq_path = '~/.local/bin/doq'
"let g:pydocstring_formatter = 'numpy'
"let g:pydocstring_templates_path = '~/correct/path'
```
and I tried also with the meaningful combinations of the commented lines.

**Comment by heavenshell** [comment]
@AleCandido 
Thx

Could you run following command at you shell?

```
cat foo.py | /path/to/doq --style=json --formatter=sphinx --omit=self,cls --indent=4 --ignore_exception
```
- `foo.py` is your python file
- `/path/to/doq` is path to your doq file

**Comment by AleCandido** [comment]
If can be useful I also tried with the older releases (tags), but for `2.0.0` and `2.1.0` it is unable to find my doq installation, but I saw that in `2.2.0` you added this `expand()` to all the occurrences of `g:pydocstring_doq_path`, so I suppose it is because my path includes `~`.

**Comment by heavenshell** [comment]
@AleCandido 
Yes, I fixed it ver 2.2.0
Could you update latest and try?

**Comment by AleCandido** [comment]
I was already on the latest, now I'm back and I tried with `cat`, but the problem is that there is no `--ignore-exception` option in `doq` (my version is `0.4.1`).

**Comment by heavenshell** [comment]
@AleCandido 
0.4.1 is old. Lataset is `0.5.1`.
Could you update doq to latest?

**Comment by AleCandido** [comment]
Sorry, I noticed just now that there is a new version of `doq`, so I upgraded, this is the output:
<details><summary>`foo.py`</summary>
<pre>
def foo(x):
    pass
</pre>
</details>

output:
```python
[{"docstring": "    \"\"\"foo.\n\n    :param x:\n    \"\"\"", "start_col": 4, "start_lineno": 1, "end_col": 0, "end_lineno": 2}]
```

**Comment by heavenshell** [comment]
Good!
So, what about run via pydocstring.vim?

**Comment by AleCandido** [comment]
I don't know, I said that `:PydocstringFormat` is working great, so I was quite sure that `doq` is working as well, but the problem is `:Pydocstring` command itself, I don't know why (the exact error is reported above).

**Comment by heavenshell** [comment]
Humm strange.
Could you record screencast(gif) and upload it to here?
I can't reploduce.

I want to see steps.

- Open vim from terminal etc
- Move to cursor to signature
- Execute :Pydocstring

**Comment by AleCandido** [comment]
Even more strange: *I am not able to reproduce anymore*.

I was trying to record as you said, so I just installed [terminalizer](https://terminalizer.com/) with `yarn global add`, and I started recording, while I was recording it worked, and since then it keeps working.

For sure I'm happy about this, and sorry about wasting your time, but I'm really puzzled about this change. For sure I was doing stuffs and manage system installations and so on, but they were decoupled from `pydocstring` and even `vim`, so I don't really know how it is possible.

Since I am not able to reproduce anymore I just give up for the time being, I will let you know if in the future I will come up with any idea, if you have suggestions I would be happy to make some other attempts.

Thank you for support, and for sure for your project :wink:.

**Comment by heavenshell** [comment]
No problem.
Great to hear you can use pydocstring.vim! 🎉

**Comment by rohan-97** [comment]
Hi @heavenshell ,

Thanks for quick reply and support.
I tried your solution and it worked fine.

Thank You!

**Comment by heavenshell** [comment]
Great! your welcome!
