### ISSUE TITLE
How to setup in order to work in Windows?

### ISSUE THREAD

**Issue by bladane** [heavenshell/vim-pydocstring#86]
I am trying to setup vim-pydocstring on Windows. But so far no success.
Vim version:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 12 2019 22:02:45)
MS-Windows 64-bit console version
```
doq is installed with pip install doq:
```
λ pip show doq
Name: doq
Version: 0.6.0
Summary: Docstring generator
Home-page: http://github.com/heavenshell/py-doq
Author: Shinya Ohyanagi
Author-email: sohyanagi@gmail.com
License: BSD
Location: c:\users\user\appdata\local\programs\python\python37\lib\site-packages
Requires: parso, jinja2
Required-by:
```
Doq is working when performing command from command line:
`λ python -m doq.cli -f fraction.py -w`
But when trying to do it from vim - it is reporting that doq is not installed.
Setup in vimrc related to pydocstring:
```
"Plugin Pydocstring setup {{{
let g:pydocstring_doq_path = 'c:/users/user/appdata/local/programs/pytho/python37/lib/site-packages/doq'
nmap <silent> <F12> <Plug>(pydocstring) 
"}}}
```

**Comment by heavenshell** [comment]
@bladane 
`let g:pydocstring_doq_path = 'c:/users/user/appdata/local/programs/pytho/python37/lib/site-packages/doq'`

`pytho` typo?

**Comment by bladane** [comment]
> @bladane
> let g:pydocstring_doq_path = 'c:/users/user/appdata/local/programs/pytho/python37/lib/site-packages/doq'
> pytho typo?

Can you elaborate. Don't understand question. I made some mistake here?

**Comment by heavenshell** [comment]
@bladane 
Does really doq exists?
```
c:/users/user/appdata/local/programs/python/python37/lib/site-packages/doq
```

In my env, `doq` is `venv/bin/doq`
```
c:/users/user/appdata/local/programs/python/python37/bin/doq
```
Does doq exists in under `bin` directory?

**Comment by bladane** [comment]
Good hint. I searched for doq.exe and found it here:
`let g:pydocstring_doq_path = 'c:\users\user\AppData\Local\Programs\Python\Python37\Scripts\doq.exe'`
And now it is working. 

Thnx.
