### ISSUE TITLE
Can't get it working with neovim

### ISSUE THREAD

**Issue by gsellers-tulco** [heavenshell/vim-pydocstring#94]
I tried installing using vim plug:
Plug 'heavenshell/vim-pydocstring', { 'do': 'make install' }

but I got this error:
`doq` not found. Install `doq`

I also checked to see if doq was installed by following the above command (docs made it sound like it would be automatically installed) but it wasn't. So I install doq via pip into my conda environment, but it still returned the same error. I tried setting the path to doq manually, but I'm not super familiar with the vim syntax for doing so, so maybe I got something wrong there.

**Comment by heavenshell** [comment]
I don't know what your OS, env etc.
It too less information.
Check your own env.


If you not familiar with vim you can read help `:h vim-script-intro`.

**Comment by gsellers-tulco** [comment]
The issue was that I was using a conda env. I found the doq binary and created a symlink as specified in the install script, and it works now.

**Comment by heavenshell** [comment]
Good news! Congrats 🎉

**Comment by gsellers-tulco** [comment]
Thanks. The vim-script help command was useful.
