### ISSUE TITLE
command not added to vim

### ISSUE THREAD

**Issue by zigi-omri** [heavenshell/vim-pydocstring#99]
Hi, great initiative :) thanks.
trying to install, I have `doq` installed. and the hook seems to run fine on `PlugInstall`. however, the command is not added to vim.
using vim version 8.2.250 on mac

Hope this helps.

**Comment by heavenshell** [comment]
@zigi-omri 
Sorry for late response.

Can you show me how to step to reproduce?
I use Vim's pack and works fine.

**Comment by zigi-omri** [comment]
Thanks @heavenshell . 
Maybe some other plugin collision?

I just followed the instructions and the command is not available in vim.
pylint + ale runs fine. anything I can do to help debug this?

**Comment by heavenshell** [comment]
@zigi-omri 
Can you try `make install`?(not using Plug)
and than can you show me gif screencapture?

- Start vim
- Enter command

Thank you

**Comment by zigi-omri** [comment]
Hi @heavenshell, please find attached the `make install` output.
didn't upload any screen capture, as there is no output when starting vim. just the usual message (version is 8.2.250), and the command, typing `:` then trying capital `P` and autocomplete will not offer anything. typing myself leads to `E492: Not an editor command: Pydocstring`

any other ideas?
![Screen Shot 2020-06-07 at 18 08 18](https://user-images.githubusercontent.com/64729248/83972786-da822f80-a8ea-11ea-9589-dabb8f371c1e.png)

**Comment by heavenshell** [comment]
@zigi-omri thx
Show me how to startup your python file.
```
vim
:e sample.py
:Pydocstring
```

or
```
vim sample.py
:Pydocstring
```

or  etc

**Comment by zigi-omri** [comment]
Hi @heavenshell,

Good news: all works. I have updated iTerm2, and now I have the command available.

Thanks for your help!
